#!/usr/bin/env python3
"""Generate Human Typer license keys.

Writes:
  - LICENSE_KEYS.txt : the plaintext keys you hand to buyers (PRIVATE — gitignored)
  - licenses.py      : SHA-256 hashes embedded in the app (safe to ship)

Only the hashes ship; the app validates a pasted key by hashing it and checking
membership, so the plaintext keys never live in the distributed app.

Usage:  python gen_licenses.py [count]   (default 50)

NOTE: re-running REPLACES the key set and invalidates previously issued keys.
To ADD more without breaking existing ones, use:  python gen_licenses.py --add N
"""
import secrets
import sys

# Unambiguous alphabet: no 0/O/1/I/L to avoid buyer typos.
ALPHABET = "ABCDEFGHJKMNPQRSTUVWXYZ23456789"
KEYS_FILE = "LICENSE_KEYS.txt"
HASHES_FILE = "licenses.py"


def _group(n=5):
    return "".join(secrets.choice(ALPHABET) for _ in range(n))


def make_key():
    return f"HT-{_group()}-{_group()}-{_group()}"


def canonical(key):
    # Must match human_typer._normalize_key: alphanumerics only, uppercased.
    return "".join(ch for ch in key if ch.isalnum()).upper()


def key_hash(key):
    import hashlib
    return hashlib.sha256(canonical(key).encode("utf-8")).hexdigest()


def read_existing_keys():
    try:
        with open(KEYS_FILE, "r", encoding="utf-8") as fh:
            return [ln.strip() for ln in fh if ln.strip() and not ln.startswith("#")]
    except FileNotFoundError:
        return []


def write(keys):
    with open(KEYS_FILE, "w", encoding="utf-8") as fh:
        fh.write("# Human Typer license keys — PRIVATE. Do not commit or publish.\n")
        fh.write("# Hand one key to each buyer. Total: %d\n\n" % len(keys))
        for i, k in enumerate(keys, 1):
            fh.write(f"{i:>3}. {k}\n")

    hashes = sorted({key_hash(k) for k in keys})
    with open(HASHES_FILE, "w", encoding="utf-8") as fh:
        fh.write('"""Embedded license-key hashes (generated by gen_licenses.py). Safe to ship."""\n')
        fh.write("LICENSE_HASHES = {\n")
        for h in hashes:
            fh.write(f'    "{h}",\n')
        fh.write("}\n")


def main():
    args = sys.argv[1:]
    add_mode = "--add" in args
    nums = [a for a in args if a.isdigit()]
    count = int(nums[0]) if nums else 50

    existing = read_existing_keys() if add_mode else []
    # strip the "  1. " numbering if present
    existing = [k.split(". ", 1)[-1] if ". " in k else k for k in existing]

    new = set()
    while len(new) < count:
        new.add(make_key())
    keys = existing + sorted(new)

    write(keys)
    print(f"{'Added' if add_mode else 'Generated'} {count} keys "
          f"({len(keys)} total) -> {KEYS_FILE} + {HASHES_FILE}")


if __name__ == "__main__":
    main()
